import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const defaultEndpoint = "https://rickandmortyapi.com/api/character/"

// interface result {
//   id: string;
//   name: string;
  
// }

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
     data 
    }
  }
}




const Home: NextPage = (data) => {
  
  const results = data;
  
  console.log('data', data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Rick & Morty Challenge 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rick & Morty Challenge 2
        </h1>

        <p className={styles.description}>
         Rick & Morty
        </p>

        <ul className={styles.grid}>
          
          {/* {results.map(result => {
            const  id, name  = result;
          })} */}
          
          <li className={styles.card}>
          <a href="https://nextjs.org/docs">
            <h3>Characters</h3>
          </a>
          </li>

        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
